--liquibase formatted sql

--changeset viktor-vv:20240702-1 failOnError:true
--comment: Create airline table.
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'airline';
create table if not exists airline
(
    id   INTEGER generated by default as identity PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

--changeset viktor-vv:20240702-2 failOnError:true
--comment: Create plane table.
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'plane';
create table if not exists plane
(
    id                  INTEGER generated by default as identity PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    year_of_manufacture INTEGER      NOT NULL,
    airline_id          INTEGER
        CONSTRAINT fk_plane_airline REFERENCES airline (id) ON DELETE SET NULL
);

--changeset viktor-vv:20240702-3 failOnError:true
--comment: Create execution_time table.
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name = 'execution_time';
create table if not exists execution_time
(
    id             INTEGER generated by default as identity PRIMARY KEY,
    method_name    VARCHAR(255) NOT NULL,
    execution_time BIGINT       NOT NULL,
    execution_type VARCHAR(50)  NOT NULL
);